version: "3.9"

services:
  db:
    image: postgres:18
    container_name: fastapi_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: fastapi_backend_app
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/

volumes:
  postgres_data: